### ISSUE TITLE
exception -> java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by xoptimal** [tianzhijiexian/CommonAdapter#29]
好像造成了死循环导致的, 

引用: 

```
mRecyclerView = (RecyclerView) findViewById(R.id.rcv);
mRecyclerView.setLayoutManager(new GridLayoutManager(RCVActivity.this, 2));
```

这里引发的问题:

```
ExRcvAdapterWrapper.class:

public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return (ViewHolder)(viewType == 99930?new ExRcvAdapterWrapper.SimpleViewHolder(this.mHeaderView):(viewType == 99931?new ExRcvAdapterWrapper.SimpleViewHolder(this.mFooterView):this.mWrapped.onCreateViewHolder(parent, viewType)));
    }
```

报错: 

```
ERR: stack=java.lang.StackOverflowError: stack size 8MB
at kale.adapter.CommonRcvAdapter.getItemType(CommonRcvAdapter.java:109)
at kale.adapter.CommonRcvAdapter.getItemViewType(CommonRcvAdapter.java:103)

```

**Comment by kaleai** [comment]
堆栈溢出了，这个问题我应该能复现。我今晚尽量解决一下。感谢你的提醒

**Comment by kaleai** [comment]
我看下你使用的地方。贴一下具体的adapter代码块

**Comment by kaleai** [comment]
你看下你是不是gettype的时候调用了某个gettype方法。产生了循环调用

**Comment by xoptimal** [comment]
adapter 没问题, 你可以尝试给recyclerView 设置如下layoutmanager 
`
mRecyclerView.setLayoutManager(new GridLayoutManager(RCVActivity.this, 2));
`

然后通过ExRcvAdapterWrapper添加一个FootView, 就会出现我说的错误了,

之前我用过是没问题的,  1.8后 就出现这个问题了,  我的adapter 没有任何问题.

我只要不setFootView 就不会出现该异常

**Comment by kaleai** [comment]
已经复现你说的问题了服，我现在正在解决中。。。

**Comment by kaleai** [comment]
我看了一下，这个是我拿列数的时候造成的循环调用，问题很奇怪，目前我简单解决了一下。代码已经提交。如果你测试没问题，我会发一个版本

**Comment by xoptimal** [comment]
ok
